### ISSUE TITLE
sizable chunk 1: test with a "real" application that will take a load

### ISSUE THREAD

**Issue by etosch** [ameetrivedi/bocado#7]
We could try setting up Django and simulate getting a lot of requests and the look at things like page load time as we sample values.

**Comment by ameetrivedi** [comment]
Need to sit with Emma for this issue resolution

**Comment by etosch** [comment]
I just started doing this with django. I'm getting some output, but it's currently still failing on a particular sample (an Option class that doesn't have a class attribute -- not sure what's going on here).

Steps:
-- clone the current django repository
-- follow the directions to run the test suite.
-- once you can run the test suite, modify `tests/runtests.py`'s main to do this:

```
   from bocado import value_sampler
    from bocado import output
    sys.settrace(value_sampler.get_fn_arg_values)

    if options.bisect:
        bisect_tests(options.bisect, options, options.modules)
    elif options.pair:
        paired_tests(options.pair, options, options.modules)
    else:
        failures = django_tests(options.verbosity, options.interactive,
                                options.failfast, options.keepdb,
                                options.reverse, options.modules,
                                options.debug_sql)
        if failures:
            sys.exit(bool(failures))

    sys.settrace(None)
    with open("EMMA_bocado_django.csv", "a") as f:
        output.pretty_print_types(stream=f)
```
-- note that you will need to re-install bocado to access the system version (which is what the above will be using). 
-- try running. right now i get this error:
```
Traceback (most recent call last):
  File "tests/runtests.py", line 424, in <module>
    output.pretty_print_types(stream=f)
  File "/Library/Python/2.7/site-packages/bocado/output.py", line 105, in pretty_print_types
    f.set_signature()
  File "/Library/Python/2.7/site-packages/bocado/classes.py", line 260, in set_signature
    self.signature[arg.argname] = (arg.position, arg.get_type())
  File "/Library/Python/2.7/site-packages/bocado/classes.py", line 133, in get_type
    tags = instance_set(self.samples)
  File "/Library/Python/2.7/site-packages/bocado/classes.py", line 31, in instance_set
    if (sample.__class__ not in dirs_by_class or
AttributeError: class Option has no attribute '__class__'
```

pitfalls: i have been having issues getting things synched up for the different version of bocado. i had found that there was something in my pythonpath that had an old version of bocado that was being masked by the appropriate version. i'm running the test suite right now calling: 
sys.path.reverse()
since when i was poking around in the repl, i found this did the trick.

**Comment by etosch** [comment]
btw after running with the `sys.path.reverse()` called before printing, i now get the error:
```
Traceback (most recent call last):
  File "tests/runtests.py", line 425, in <module>
    output.pretty_print_types(stream=f)
  File "/Library/Python/2.7/site-packages/bocado/output.py", line 105, in pretty_print_types
    f.set_signature()
  File "/Library/Python/2.7/site-packages/bocado/classes.py", line 263, in set_signature
    self.signature[arg.argname] = (arg.position, arg.get_type())
  File "/Library/Python/2.7/site-packages/bocado/classes.py", line 136, in get_type
    tags = instance_set(self.samples)
  File "/Library/Python/2.7/site-packages/bocado/classes.py", line 26, in instance_set
    type_set.add(ParameterizedList(instance_set(sample)))
  File "/Library/Python/2.7/site-packages/bocado/classes.py", line 392, in __new__
    assert len(tags) == len(set(tags)), "Lists are unordered and should not contain multiples."
AssertionError: Lists are unordered and should not contain multiples.
```

I'm looking into where multiples are introduced.

**Comment by etosch** [comment]
```
    from bocado import value_sampler
    from bocado import output
    sys.settrace(value_sampler.get_fn_arg_values)

    if options.bisect:
        bisect_tests(options.bisect, options, options.modules)
    elif options.pair:
        paired_tests(options.pair, options, options.modules)
    else:
        failures = django_tests(options.verbosity, options.interactive,
                                options.failfast, options.keepdb,
                                options.reverse, options.modules,
                                options.debug_sql)
        if failures:
            sys.exit(bool(failures))

    sys.settrace(None)

    import traceback
    sys.path = ["/usr/local/lib/python2.7/site-packages"]
    with open("EMMA_bocado_django.txt", "a") as f:
        try:
            output.pretty_print_types(stream=f)
        except:
            tb = traceback.format_exc()
        else:
            tb = "No error"
        finally:
            print tb
```

Now it runs with no errors.
